# FAQ https://stackoverflow.com/questions/48197580/jekyll-theme-does-not-work-on-github-pages-but-works-locally
permalink:           pretty

# Setup
title:               'My Mac Setup'
url:                 https://nhtlongcs.github.io
baseurl:             '/my-mac-setup' # / + your base url 
homepage_title:      Home
default_lang:        'en'

# About/contact
author:
name:                nhtlongcs
url:                 https://twitter.com/nhtlongcs
github:
  repo:              https://github.com/nhtlongcs/my-mac-setup

# Custom vars
version:             0.0.1

src:                 "."
default_theme:       "ayu"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "custom"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: null

exclude:
  - jekyllbook
  - en/index.md
  - vendor

################################### English ####################################
prologues:
  - path: en/faq.md
  - path: en/about.md
chapters:
  - path: en/Xcode/README.md
    sections: []
  - path: en/Vim/README.md
    sections: []
  - path: en/PostgreSQL/README.md
    sections: []
  - path: en/iTerm/README.md
    sections:
    - path: en/iTerm/autojump.md
    - path: en/iTerm/tree.md
    - path: en/iTerm/ack.md
    - path: en/iTerm/zsh.md
    - path: en/iTerm/fzf.md
  - path: en/Docker/README.md
    sections:
    - path: en/Docker/UsefulCommands.md
    - path: en/Docker/TipsAndTricks.md
  - path: en/SystemPreferences/README.md
    sections: []
  - path: en/Go/README.md
    sections: []
  - path: en/Heroku/README.md
    sections: []
  - path: en/SublimeText/README.md
    sections:
    - path: en/SublimeText/SublimeLinter.md
    - path: en/SublimeText/Plugins.md
    - path: en/SublimeText/Packages.md
    - path: en/SublimeText/Preferences.md
  - path: en/Python/README.md
    sections:
    - path: en/Python/ipython.md
    - path: en/Python/virtualenv.md
    - path: en/Python/pip.md
    - path: en/Python/numpy.md
  - path: en/Security/README.md
    sections: []
  - path: en/References/README.md
    sections: []
  - path: en/Vagrant/README.md
    sections: []
  - path: en/LaTeX/README.md
    sections: []
  - path: en/MyySQL/README.md
    sections: []
  - path: en/Rust/README.md
    sections: []
  - path: en/Homebrew/README.md
    sections:
    - path: en/Homebrew/Cask.md
    - path: en/Homebrew/Usage.md
  - path: en/Emacs/README.md
    sections: []
  - path: en/BashCompletion/README.md
    sections: []
  - path: en/Node.js/README.md
    sections: []
  - path: en/Scala/README.md
    sections: []
  - path: en/Cpp/README.md
    sections: []
  - path: en/Sudo/README.md
    sections: []
  - path: en/VisualStudioCode/README.md
    sections: []
  - path: en/Apps/README.md
    sections:
    - path: en/Apps/Settings.md
    - path: en/Apps/Octave.md
  - path: en/Ruby/README.md
    sections:
    - path: en/Ruby/RubyGems.md
  - path: en/Git/README.md
    sections:
    - path: en/Git/gitignore.md


#  - path: chapters/end.md

# ################################### Mandarin ###################################
# zh:
#   title: '深度学习'
#   prologues:
#     - path: zh/about.md
#   chapters:
#     - path: zh/week01/01.md
#       sections:
#         - path: zh/week01/01-1.md
#         - path: zh/week01/01-2.md
#         - path: zh/week01/01-3.md
#     - path: zh/week02/02.md
#       sections:
#         - path: zh/week02/02-1.md
#         - path: zh/week02/02-2.md
#         - path: zh/week02/02-3.md
#     - path: zh/week03/03.md
#       sections:
#         - path: zh/week03/03-1.md
#         - path: zh/week03/03-2.md
#         - path: zh/week03/03-3.md
#     - path: zh/week04/04.md
#       sections:
#         - path: zh/week04/04-1.md
#     - path: zh/week05/05.md
#       sections:
#         - path: zh/week05/05-1.md
#         - path: zh/week05/05-2.md
#         - path: zh/week05/05-3.md
#     - path: zh/week06/06.md
#       sections:
#         - path: zh/week06/06-1.md
#         - path: zh/week06/06-2.md
#         - path: zh/week06/06-3.md
#     - path: zh/week07/07.md
#       sections:
#         - path: zh/week07/07-1.md
#         - path: zh/week07/07-2.md
#         - path: zh/week07/07-3.md
#     - path: zh/week08/08.md
#       sections:
#         - path: zh/week08/08-1.md
#         - path: zh/week08/08-2.md
#         - path: zh/week08/08-3.md
#     - path: zh/week09/09.md
#       sections:
#         - path: zh/week09/09-1.md
#         - path: zh/week09/09-2.md
#         - path: zh/week09/09-3.md
#     - path: zh/week10/10.md
#       sections:
#         - path: zh/week10/10-1.md
#         - path: zh/week10/10-2.md
#         - path: zh/week10/10-3.md
#     - path: zh/week11/11.md
#       sections:
#         - path: zh/week11/11-1.md
#         - path: zh/week11/11-2.md
#         - path: zh/week11/11-3.md
#     - path: zh/week12/12.md
#       sections:
#         - path: zh/week12/12-1.md
#         - path: zh/week12/12-2.md
#         - path: zh/week12/12-3.md
#     - path: zh/week13/13.md
#       sections:
#         - path: zh/week13/13-1.md
#         - path: zh/week13/13-2.md
#         - path: zh/week13/13-3.md
#     - path: zh/week14/14.md
#       sections:
#         - path: zh/week14/14-1.md
#         - path: zh/week14/14-2.md
#         - path: zh/week14/14-3.md
#     - path: zh/week15/15.md
#       sections:
#         - path: zh/week15/15-1.md
#         - path: zh/week15/15-2.md
